server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848
        # nginx端口配置，nginx配置nacos集群，并连接mysql数据库
        server-addr: 192.168.51.100:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'